runtime: php55
api_version: 1

handlers:
- url: /ctrlpanel.php
  script: ctrlpanel.php
- url: /service.php
  script: server.php
- url: /manage.php
  script: manage.php
- url: /ctrlpanel_files
  static_dir: ctrlpanel_files
- url: /
  script: client.php

# [START env]
env_variables:
  # Replace USER, PASSWORD, DATABASE, and CONNECTION_NAME with the
  # values obtained when configuring your Cloud SQL instance.
  MYSQL_DSN: mysql:unix_socket=/cloudsql/my-visit-counter:us-central1:myvisitcounterdb;dbname=counterdb
  MYSQL_USER: mvc-app
  MYSQL_PASSWORD: '239}=9/##f9ohU8jA?'
# [END env]
